# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/bitnamisecure/wordpress
  pullPolicy: IfNotPresent
  tag: latest@sha256:ee29a4271e954d6a64c5af9b4a5ba5d896b975c6e7ab2882d1036caf5ccf3df5
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          envFrom:
            - configMapRef:
                name: env-config
            - secretRef:
                name: env-secret
          probes:
            liveness:
              enabled: true
              type: tcp
              port: "{{ .Values.service.main.ports.main.port }}"
            readiness:
              enabled: true
              type: tcp
              port: "{{ .Values.service.main.ports.main.port }}"
            startup:
              enabled: true
              type: tcp
              port: "{{ .Values.service.main.ports.main.port }}"
wordpress:
  user: user
  pass: bitnami
  email: user@example.com
  first_name: TrueCharts
  last_name: TrueCharts
  blog_name: Truecharts Blog
  enable_reverse_proxy_headers: true
smtp:
  enabled: false
  host: ""
  port: 587
  user: ""
  pass: ""
php-config:
  PHP_ENABLE_OPCACHE: "yes"
  PHP_EXPOSE_PHP: ""
  PHP_MAX_EXECUTION_TIME: ""
  PHP_MAX_INPUT_TIME: ""
  PHP_MAX_INPUT_VARS: ""
  PHP_MEMORY_LIMIT: 512M
  PHP_POST_MAX_SIZE: ""
  PHP_UPLOAD_MAX_FILESIZE: ""
service:
  main:
    ports:
      main:
        protocol: http
        port: 10591
persistence:
  config:
    enabled: true
    mountPath: /bitnami/wordpress
mariadb:
  enabled: true
  mariadbUsername: wordpress
  mariadbDatabase: wordpress
