# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/universalmediaserver/ums
  tag: latest@sha256:29b23f05c23ba63582490b5ebee106811631aa50052143bed90c104039ee5b83
persistence:
  config:
    enabled: true
    mountPath: /root/.config/UMS/
  media:
    enabled: true
    mountPath: /media

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  api:
    enabled: true
    ports:
      api:
        enabled: true
        port: 5001
        protocol: tcp
        targetPort: 5001
  main:
    ports:
      main:
        port: 9001
        protocol: http
        targetPort: 9001
  sub:
    enabled: true
    ports:
      sub:
        enabled: true
        port: 1044
        protocol: tcp
        targetPort: 1044
