# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/aeonlucid/impostor
  tag: nightly@sha256:ade42ad220631a4a73d00cdac7fc826126cb64ec9437bff971238f69a5edaad6
  pullPolicy: IfNotPresent
