# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/traggo/server
  pullPolicy: IfNotPresent
  tag: 0.8.3@sha256:8bf510774ce1729b5bd9a8930e174de03ebec8c25ca4aaa087c0e56e2bcbb67a
traggo:
  username: admin
  password: admin
  pass_strength: 10
  log_level: info
service:
  main:
    ports:
      main:
        protocol: http
        port: 12117
persistence:
  config:
    enabled: true
    mountPath: /opt/traggo/data

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
            readiness:
              type: http
            startup:
              type: http
          envFrom:
            - secretRef:
                name: "secret"
