# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/haveagitgat/tdarr
  pullPolicy: IfNotPresent
  tag: 2.59.01@sha256:95ee0aa8817c2479fc8638f9af769bd65be005ad0230f49e7f0c4c1e3eff3c55
service:
  main:
    ports:
      main:
        port: 8265
  comm:
    enabled: true
    ports:
      comm:
        enabled: true
        port: 8266
persistence:
  configs:
    enabled: true
    mountPath: "/app/configs"
  server:
    enabled: true
    mountPath: "/app/server"
  logs:
    enabled: true
    mountPath: "/app/logs"
  transcode-cache:
    enabled: true
    mountPath: "/temp"
  media:
    enabled: true
    mountPath: "/media"
  varrun:
    enabled: true

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            webUIPort: "{{ .Values.service.main.ports.main.port }}"
            serverPort: "{{ .Values.service.comm.ports.comm.port }}"
            # User Defined
            internalNode: true
            serverIP: "127.0.0.1"
            nodeID: "Internal Node"
