# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/anotherstranger/borg-server
  pullPolicy: IfNotPresent
  tag: 2.8.1@sha256:22118deb20c06e8fa0b7c9c60dc057a640b893961fafa9f9e9d64c8ee2f3542c

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: tcp
        targetPort: 22
        port: 8022

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            BORG_UID: "{{ .Values.securityContext.container.PUID }}"
            BORG_GID: "{{ .Values.securityContext.pod.fsGroup }}"
          securityContext:
            capabilities:
              add:
                - SYS_CHROOT
                - KILL

persistence:
  borg:
    enabled: true
    mountPath: "/var/lib/docker-borg"
  backups:
    enabled: true
    mountPath: "/home/borg/backups"
  ssh:
    enabled: true
    mountPath: "/home/borg/.ssh"
