# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/jlesage/mkvtoolnix
  tag: v26.02.1@sha256:33809a82a8ac4727da9444c167f4e6bc858d38395554ad0fe0e3bc91b35248dc
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10236
        targetPort: 5800
  vnc:
    enabled: true
    ports:
      vnc:
        enabled: true
        port: 10237
        targetPort: 5900
mkvtoolnix:
  # General Settings
  KEEP_APP_RUNNING: false
  # GUI Settings
  DISPLAY_WIDTH: 1280
  DISPLAY_HEIGHT: 768
  DARK_MODE: false
  # App Settings
  SECURE_CONNECTION: false
  ENABLE_CJK_FONT: false
configmap:
  mkvtoolnix:
    enabled: true
    data:
      ENABLE_CJK_FONT: '{{ ternary "1" "0" .Values.mkvtoolnix.ENABLE_CJK_FONT }}'
      KEEP_APP_RUNNING: '{{ ternary "1" "0" .Values.mkvtoolnix.KEEP_APP_RUNNING }}'
      SECURE_CONNECTION: '{{ ternary "1" "0" .Values.mkvtoolnix.SECURE_CONNECTION }}'
      DISPLAY_WIDTH: "{{ .Values.mkvtoolnix.DISPLAY_WIDTH }}"
      DISPLAY_HEIGHT: "{{ .Values.mkvtoolnix.DISPLAY_HEIGHT }}"
      DARK_MODE: '{{ ternary "1" "0" .Values.mkvtoolnix.DARK_MODE }}'
persistence:
  config:
    enabled: true
    mountPath: "/config"
  storage:
    enabled: true
    mountPath: "/storage"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
                - KILL
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
          env:
            VNC_PASSWORD: ""
          envFrom:
            - configMapRef:
                name: "mkvtoolnix"
