# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: oci.trueforge.org/containerforge/duplicacy
  tag: 1.8.0@sha256:d26525a1dae01693a0ea679ba61e7b9961c13d36aa5c00cfdea3f43d98b970fa
securityContext:
  container:
    runAsGroup: 0
    runAsUser: 0
    readOnlyRootFilesystem: false
service:
  main:
    ports:
      main:
        port: 3875
        protocol: http
        targetPort: 3875
persistence:
  config:
    enabled: true
    mountPath: /config
  cache:
    enabled: true
    mountPath: /cache
  logs:
    enabled: true
    mountPath: /logs
