image:
  repository: docker.io/anirdev/slink
  pullPolicy: IfNotPresent
  tag: v1.9.5@sha256:ba21f44c3937c5a614e2f7e1717fafa86d776e085f1ac94932e3053a120dddd6
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
    runAsNonRoot: false
service:
  main:
    ports:
      main:
        protocol: http
        port: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ORIGIN: "{{ .Values.chartContext.appUrl }}"
            USER_APPROVAL_REQUIRED: true
            IMAGE_MAX_SIZE: "15M"
persistence:
  database:
    enabled: true
    mountPath: "/app/var/data"
  images:
    enabled: true
    mountPath: "/app/slink/images"
ingress:
  main:
    required: true
