# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/chroma-core/chroma
  pullPolicy: IfNotPresent
  tag: 1.5.0@sha256:254a00413c12178c974d93a518ec000235efb3f700af7e61471f4b3507049a8a

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8000
        port: 10690

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/api/v2/heartbeat"
            readiness:
              path: "/api/v2/heartbeat"
            startup:
              path: "/api/v2/heartbeat"
          env:
            IS_PERSISTENT: true

persistence:
  config:
    enabled: true
    mountPath: "/chroma/chroma"
